### ISSUE TITLE
Upgrade for compatibility with Datasette 0.44+

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-upload-csvs#11]
Similar to https://github.com/simonw/datasette-configure-fts/issues/9

**Comment by simonw** [comment]
Getting this error with Datasette 045 at the moment even though the tests are passing:
```
datasette .
INFO:     Started server process [13493]
INFO:     Waiting for application startup.
ERROR:    Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/datasette-upload-csvs-Tx5Sw3VW/lib/python3.7/site-packages/uvicorn/lifespan/on.py", line 48, in main
    await app(scope, self.receive, self.send)
  File "/Users/simon/.local/share/virtualenvs/datasette-upload-csvs-Tx5Sw3VW/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/simon/Dropbox/Development/datasette-upload-csvs/datasette_upload_csvs/__init__.py", line 9, in wrapped_app
    if scope["path"] == "/-/upload-csv":
KeyError: 'path'
ERROR:    Application startup failed. Exiting.
```

**Comment by simonw** [comment]
Next step: replace Starlette with `register_routes`.

**Comment by simonw** [comment]
Actually no - we still need Starlette because we need to handle form uploads. Hopefully can reuse the Starlette request class here against `scope` and `receive` arguments.

**Comment by simonw** [comment]
Big problem: I just got this error
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/datasette-upload-csvs-Tx5Sw3VW/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/simon/.local/share/virtualenvs/datasette-upload-csvs-Tx5Sw3VW/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/simon/.local/share/virtualenvs/datasette-upload-csvs-Tx5Sw3VW/lib/python3.7/site-packages/datasette/utils/asgi.py", line 147, in __call__
    await self.app(scope, receive, send)
  File "/Users/simon/.local/share/virtualenvs/datasette-upload-csvs-Tx5Sw3VW/lib/python3.7/site-packages/datasette/tracer.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/Users/simon/.local/share/virtualenvs/datasette-upload-csvs-Tx5Sw3VW/lib/python3.7/site-packages/asgi_csrf.py", line 139, in app_wrapped_with_csrf
    assert False, "multipart/form-data is not yet supported"
AssertionError: multipart/form-data is not yet supported
```
Do I need to implement multipart form data in `asgi-csrf` or can I get away with disabling CSRF checks for these uploads?

**Comment by simonw** [comment]
Frustratingly I think I need `multipart/form-data` support, see https://github.com/simonw/asgi-csrf/issues/1
